import fs from 'node:fs';
import { nodes, edges, characters, kernelStages, evidence } from '../data/lineage.js';

const fail = msg => { console.error(`FAIL: ${msg}`); process.exitCode = 1; };
const ids = new Set(nodes.map(n => n.id));
if (ids.size !== nodes.length) fail('node IDs are not unique');
for (const e of edges) {
  if (!ids.has(e.source)) fail(`missing edge source ${e.source}`);
  if (!ids.has(e.target)) fail(`missing edge target ${e.target}`);
  if (!['body','macro'].includes(e.type)) fail(`invalid edge type ${e.type}`);
}
for (const n of nodes) {
  if (!['canon','unknown','provisional'].includes(n.status)) fail(`invalid node status ${n.status}`);
  for (const key of ['name','function','topology','evidence']) if (!n[key]) fail(`${n.id} missing ${key}`);
}
if (!characters.length) fail('character matrix is empty');
if (!kernelStages.some(s=>s.status==='unknown')) fail('Mother Kernel must preserve unknown states');
if (!evidence.some(e=>e.authorial.includes('NOT YET') || e.authorial.includes('REJECTED'))) fail('evidence ledger lacks uncertainty/rejection state');
for (const file of ['index.html','styles.css','app.js','README.md','data/schema.json']) if(!fs.existsSync(new URL(`../${file}`,import.meta.url))) fail(`missing ${file}`);
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
if (!html.includes('Morphogenesis Compiler')) fail('compiler view missing');
if (!html.includes('Evidence & Paleontology')) fail('two-truths view missing');
if (html.match(/ChatGPT|OpenAI|Claude|Gemini|generated by/gi)) fail('production-system residue detected');
if (!process.exitCode) console.log(`PASS: ${nodes.length} nodes, ${edges.length} edges, ${characters.length} characters, ${kernelStages.length} kernel stages.`);
