import fs from 'node:fs';
import { nodes, strains, archetypes, edges, characters, kernelStages, evidence, sourceRefs, catalogConflict } from '../data/lineage.js';

const fail = msg => { console.error(`FAIL: ${msg}`); process.exitCode = 1; };
const ids = new Set(nodes.map(n => n.id));
if (ids.size !== nodes.length) fail('node IDs are not unique');
if (strains.length !== 58) fail(`expected 58 integrated strain records, found ${strains.length}`);
if (archetypes.length !== 8) fail(`expected 8 integrated family labels, found ${archetypes.length}`);
if (strains.filter(s=>s.catalogTier==='core-35').length !== 35) fail('core-count roster must contain exactly 35 strains');
if (strains.filter(s=>s.catalogTier!=='core-35').length !== 23) fail('integrated expansion must contain exactly 23 additional strains');
if (catalogConflict.integratedEntries !== 60 || catalogConflict.laterMetaEntries !== 37) fail('catalog-count conflict is not encoded correctly');

const expectedNames = [
  "MAGMA PLEURON",
  "GRANITHELION",
  "FAULT-TONGUE",
  "OBSIDIAN GUL",
  "TREMORHOUND",
  "GLASSSPINE",
  "QUARRYMIND",
  "AEROKARST",
  "CLOUDMAW",
  "ATMANTID",
  "WEATHERNODE",
  "VORTENBRAY",
  "FUMERICUS",
  "SKYMOURN",
  "VERDGORGE",
  "POLLENVAULT",
  "MYCETHRON",
  "RAINTASTER",
  "TERRAGULLET",
  "PETALNEST",
  "FERALSEED",
  "ABYSSORIEL",
  "BRINECHOIR",
  "CURRENTHALO",
  "SHELFCARVER",
  "GLACIERTHROAT",
  "VEILCURRENT",
  "CORONAXIS",
  "RINGTHROAT",
  "SOLNEXUS",
  "NULLTHORN",
  "LYRIBORIS",
  "HELIONTH",
  "UMBRAKRAEL",
  "CINDERVERGE",
  "SINGULARARCH",
  "IRONCANT",
  "GRIDSAINT",
  "SPIREMOLT",
  "ROADTHORN",
  "HABITARCH",
  "ARCHIVORE",
  "HARBORHEX",
  "GOREVAULT",
  "LEXICLAST",
  "CALENDARION",
  "DREAMTAXON",
  "CROWNMUTE",
  "HYMNLOCK",
  "MEMORIALVEIN",
  "SHRINEHUNGER",
  "REDACTED GRIN",
  "SPINAL LOOP",
  "CRADLE.EXE",
  "FOLDHOWL",
  "MANIFEST.DISCORD",
  "GLORYFAIL",
  "VIRAL BASTION"
];
for (const name of expectedNames) if (!strains.some(s=>s.name===name)) fail(`missing Compendium strain ${name}`);
for (const locked of ['RINGTHROAT','GOREVAULT']) {
  const s=strains.find(x=>x.name===locked);
  if (!s || s.status!=='canon' || s.catalogTier!=='locked-expansion') fail(`${locked} must remain a locked expansion entry`);
}
for (const e of edges) {
  if (!ids.has(e.source)) fail(`missing edge source ${e.source}`);
  if (!ids.has(e.target)) fail(`missing edge target ${e.target}`);
  if (!['body','macro'].includes(e.type)) fail(`invalid edge type ${e.type}`);
}
for (const n of nodes) {
  if (!['canon','unknown','provisional'].includes(n.status)) fail(`invalid node status ${n.status}`);
  for (const key of ['name','function','topology','evidence']) if (!n[key]) fail(`${n.id} missing ${key}`);
}
for (const s of strains) {
  for (const key of ['group','subtype','affinity','threat','timescale','topology','function','tactical','lore','catalogTier']) if (!s[key]) fail(`${s.name} missing ${key}`);
  if (!s.sourceBacked) fail(`${s.name} must retain sourceBacked=true`);
}
if (!characters.length) fail('character matrix is empty');
if (!kernelStages.some(s=>s.status==='unknown')) fail('Mother Kernel must preserve unknown states');
if (!evidence.some(e=>/37 entries|35 strains/i.test(e.claim))) fail('catalog count conflict evidence is missing');
if (sourceRefs.length < 4) fail('source cross-check inventory is incomplete');

for (const file of ['index.html','styles.css','app.js','README.md','data/schema.json']) if(!fs.existsSync(new URL(`../${file}`,import.meta.url))) fail(`missing ${file}`);
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
if (!html.includes('Morphogenesis Compiler')) fail('compiler view missing');
if (!html.includes('Evidence & Paleontology')) fail('two-truths view missing');
if (!html.includes('networkGroup') || !html.includes('registryGroup')) fail('full-roster family filters missing');
if (!html.includes('catalogConflictCard')) fail('catalog conflict UI missing');
if (html.match(/ChatGPT|OpenAI|Claude|Gemini|generated by/gi)) fail('production-system residue detected');

const publicData = JSON.stringify({nodes,strains,archetypes,sourceRefs,evidence});
const forbidden = [/drive\.google\.com/i,/\/Users\//i,/file_[0-9a-f]{12,}/i,/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i];
for (const p of forbidden) if (p.test(publicData)) fail(`private source metadata leaked: ${p}`);

if (!process.exitCode) console.log(`PASS: ${strains.length} strains, ${archetypes.length} families, ${edges.length} lineage edges; catalog conflict preserved.`);
